# Generating results and statistics for Table 1

######### Summary Statistics #########
#########                    #########

advanced_all_weeklyspending_model_coef <- coef(advanced_all_weeklyspending_model)
advanced_acf_weeklyspending_model_coef <- coef(advanced_acf_weeklyspending_model)
Spending_in_restrictions <- Spending_Weekly_Data %>%
  filter(Restricted == 1)
Spending_outof_restrictions <- Spending_Weekly_Data %>%
  filter(Restricted == 0)
Unemployment_in_restrictions <- Cleaned_Unemployment_Data %>%
  filter(Restricted == 1)
Unemployment_outof_restrictions <- Cleaned_Unemployment_Data %>%
  filter(Restricted == 0)

summary_stats_mean <- numeric()
summary_stats_sd <- numeric()
summary_stats_num_obs <- numeric()
summary_stats_labels <- character()
summary_stats_labels <- append(summary_stats_labels, "acfspending in restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_in_restrictions$spend_acf))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_in_restrictions$spend_acf))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_in_restrictions$spend_acf))
summary_stats_labels <- append(summary_stats_labels, "allspending in restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_in_restrictions$spend_all))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_in_restrictions$spend_all))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_in_restrictions$spend_all))
summary_stats_labels <- append(summary_stats_labels, "NewCases in restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_in_restrictions$NewCases))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_in_restrictions$NewCases))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_in_restrictions$NewCases))
summary_stats_labels <- append(summary_stats_labels, "NewDeaths in restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_in_restrictions$NewDeaths))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_in_restrictions$NewDeaths))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_in_restrictions$NewDeaths))
summary_stats_labels <- append(summary_stats_labels, "DeltaNewCases in restrictions ")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_in_restrictions$DeltaNewCases))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_in_restrictions$DeltaNewCases))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_in_restrictions$DeltaNewCases))
summary_stats_labels <- append(summary_stats_labels, "DeltaNewDeaths in restrictions") 
summary_stats_mean <- append(summary_stats_mean, mean(Spending_in_restrictions$DeltaNewDeaths))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_in_restrictions$DeltaNewDeaths))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_in_restrictions$DeltaNewDeaths))
summary_stats_labels <- append(summary_stats_labels, "Initial Claims Rate in restrictions") 
summary_stats_mean <- append(summary_stats_mean, mean(Unemployment_in_restrictions$initclaims_rate_regular))
summary_stats_sd <- append(summary_stats_sd, sd(Unemployment_in_restrictions$initclaims_rate_regular))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Unemployment_in_restrictions$initclaims_rate_regular))

summary_stats_labels <- append(summary_stats_labels, "acfspending out of restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_outof_restrictions$spend_acf))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_outof_restrictions$spend_acf))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_outof_restrictions$spend_acf))
summary_stats_labels <- append(summary_stats_labels, "allspending out of restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_outof_restrictions$spend_all))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_outof_restrictions$spend_all))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_outof_restrictions$spend_all))
summary_stats_labels <- append(summary_stats_labels, "NewCases out of restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_outof_restrictions$NewCases))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_outof_restrictions$NewCases))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_outof_restrictions$NewCases))
summary_stats_labels <- append(summary_stats_labels, "NewDeaths out of restrictions")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_outof_restrictions$NewDeaths))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_outof_restrictions$NewDeaths))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_outof_restrictions$NewDeaths))
summary_stats_labels <- append(summary_stats_labels, "DeltaNewCases out of restrictions ")
summary_stats_mean <- append(summary_stats_mean, mean(Spending_outof_restrictions$DeltaNewCases))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_outof_restrictions$DeltaNewCases))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_outof_restrictions$DeltaNewCases))
summary_stats_labels <- append(summary_stats_labels, "DeltaNewDeaths out of restrictions") 
summary_stats_mean <- append(summary_stats_mean, mean(Spending_outof_restrictions$DeltaNewDeaths))
summary_stats_sd <- append(summary_stats_sd, sd(Spending_outof_restrictions$DeltaNewDeaths))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Spending_outof_restrictions$DeltaNewDeaths))
summary_stats_labels <- append(summary_stats_labels, "Initial Claims Rate out of restrictions") 
summary_stats_mean <- append(summary_stats_mean, mean(Unemployment_outof_restrictions$initclaims_rate_regular))
summary_stats_sd <- append(summary_stats_sd, sd(Unemployment_outof_restrictions$initclaims_rate_regular))
summary_stats_num_obs <- append(summary_stats_num_obs, length(Unemployment_outof_restrictions$initclaims_rate_regular))

Summary_Stats_Table <- data.frame(summary_stats_labels, summary_stats_mean, summary_stats_sd, summary_stats_num_obs)

write.csv(Summary_Stats_Table, "summary_stats_table.csv")
